parameters:
    # Value converters
    ezpublish.fieldType.ezprice.converter.class: BrunoChirez\FieldTypeBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Price

services:
    ezpublish.fieldType.ezprice.converter:
        class: %ezpublish.fieldType.ezprice.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezprice, lazy: true, callback: '::create'}